### PR TITLE
Add Htool

### PR DESCRIPTION
**Pull request by PierreMarchand20**

### CODE REVIEW

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 , 

Thanks again!
I have run your PR on AWS, and spotted two main warnings:
1. When installing the library, there was initially an installation error with missing mpi4py. My understanding is that the error is first detected, but that the docker file installed it afterwards. Is this expected behavior? Shouldn't we simply install mpi4py first?
2. While running H-Tool, a common warning was `Parameter 10 to routine DGEMM  was incorrect`.

I also encountered issues with the singularity at zero for the inverse-distance kernel with BruteForceSolverLAPACK in float32 and float64 precision, but this is not related to H-Tool.

See you soon :-)
Jean

**Comment by jeanfeydy** [comment]
I have put the website online. There are clearly some problems, but they are probably due to the singularity at zero, NaNs, etc.
If the two points above are fine for you, we can probably merge the PR and discuss about a clean behavior for the inverse-distance kernel at some point next week.

**Comment by PierreMarchand20** [comment]
> 1. When installing the library, there was initially an installation error with missing mpi4py. My understanding is that the error is first detected, but that the docker file installed it afterwards. Is this expected behavior? Shouldn't we simply install mpi4py first?

The way `setup.py` works is a little bit mysterious to me, for some reasons it seemed `install_requires` is called after `cmdclass`, but luckily, the install process is triggered twice o_O to avoid this I added a `requirements.txt` file and call `pip3 install -r requirements.txt` first.

> 2. While running H-Tool, a common warning was `Parameter 10 to routine DGEMM  was incorrect`.

This must be an issue from my interface not taking the right size somewhere, and I would suggest to wait that I fix this before merging. Any idea how I could reproduce the issue ? I tried `python3.9 run.py --local --algorithm htool-product` but I did not get any warning, and I also tried `python3.9 run.py  --algorithm htool-product`, but I got 
```
2022-01-30 16:47:13,760 - kmb - INFO - Order: [Definition(algorithm='htool-product', constructor='HtoolProduct', module='kernel_matrix_benchmarks.algorithms.htool', docker_tag='kernel-matrix-benchmarks-htool', arguments={'kernel': 'inverse-distance', 'dimension': 3, 'normalize_rows': False, 'eta': 100, 'epsilon': 0.001, 'source_minclustersize': 100, 'symmetry': 'S', 'UPLO': 'L'}, query_argument_groups=[{}])]
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "*********/kernel-matrix-benchmarks/kernel_matrix_benchmarks/main.py", line 64, in run_worker
    run_docker(
  File "File "*********/kernel-matrix-benchmarks/kernel_matrix_benchmarks/runner.py", line 274, in run_docker
    container = client.containers.run(
  File "/usr/local/lib/python3.9/site-packages/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.9/site-packages/docker/models/containers.py", line 878, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 428, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.9/site-packages/docker/api/container.py", line 439, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("Requested CPUs are not available - requested 0-7, available: 0-3")
```

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 ,

I see, thanks!
To answer your points:

1. Where did you commit this change? And isn’t it simply a matter of including mpi4py as a dependency of htool?
2. Beware: run.py only runs the benchmarks on a single dataset! Default currently is the sphere with 1000 points, as written [here](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/d31eac1b226358abd2e018493f5671b5a303d9dd/kernel_matrix_benchmarks/main.py#L85). In practice, you probably want to run the [create_website_local.sh](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/master/create_website_local.sh) script to test things.
3. As for your docker error, there seems to be an issue with the detection of available cpus [here](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/d31eac1b226358abd2e018493f5671b5a303d9dd/kernel_matrix_benchmarks/main.py#L63). You could maybe change the value by hand to investigate the issue?

See you soon,
Jean

**Comment by PierreMarchand20** [comment]
> 1. Where did you commit this change? 

Sorry, I was waiting to fix point 2, but I just pushed it.

> And isn’t it simply a matter of including mpi4py as a dependency of htool?

I am not sure I understand, isn't what putting mpi4py in `requirements.txt` means ?

> 2. Beware: run.py only runs the benchmarks on a single dataset! Default currently is the sphere with 1000 points, as written [here](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/d31eac1b226358abd2e018493f5671b5a303d9dd/kernel_matrix_benchmarks/main.py#L85). In practice, you probably want to run the [create_website_local.sh](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/master/create_website_local.sh) script to test things.

Thank you for the clarification. I tried the three datasets for the product, I did not get this warning locally. With the docker containers, I do not get any output, do you know how could I increase verbosity?

> 3. As for your docker error, there seems to be an issue with the detection of available cpus [here](https://github.com/kernel-matrix-benchmarks/kernel-matrix-benchmarks/blob/d31eac1b226358abd2e018493f5671b5a303d9dd/kernel_matrix_benchmarks/main.py#L63). You could maybe change the value by hand to investigate the issue?

I see. I do not know on other OS, but on macOS, Docker desktop puts a limit on 4 CPUs by default. But the cpu limit on my laptop is 8, which is why it fails, it tries to use up to 8 cpus, but Docker desktop can only see up to 4.

image

I quickly looked in the API of *Docker SDK for Python*, but I could not find a way to get these values. I guess we can always put an issue there if we want to make `run.py` more robust.


As a side note, I tried using black for formatting, but it still modifies the style of most of python files. Do you use it with some specific options? In any case, since you have added a `.vscode/settings.json` file, we could add `"python.formatting.provider": "black"`.

**Comment by PierreMarchand20** [comment]
One thing I was thinking when writing this PR is that may be we should clarify what can be done when preparing data. For example, I renumber the geometric points according to a hierarchical clustering to improve compression. Can I permute the signal source according to this new numbering in `prepare_query` to avoid the permutation in `query`? 

Just a thought, I am not expecting an answer. I guess we should discuss this with the others at some point.

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 ,

I see, thanks!
To follow-up on your points:

1. I was talking about adding mpi4py in the `install_requires` field of setup.py. But you seem to have done this [already](https://github.com/PierreMarchand20/htool-kernel-matrix-benchmarks/blob/b151a7d96d78e89c61f8ed3294821ea067e054c7/setup.py#L80)?
2. I'm a bit surprised to read that you didn't get any output in the terminal. But anyway, everything important should be in the file `kmb.log`, that you can read with e.g. `less -R kmb.log` (with colors!). For reference, in my instance, one of the experiments outputs:

```log
2022-01-29 16:36:02,453 - kmb.a4977f7650 - INFO - Created container a4977f7650: CPU limit 0-63, mem limit 530732960512, timeout 1200, command ['--dataset', 'product-sphere-D3-E1-M5000-
N5000-inverse-distance', '--algorithm', 'htool-product', '--module', 'kernel_matrix_benchmarks.algorithms.htool', '--constructor', 'HtoolProduct', '--runs', '2', '{"kernel": "inverse-d
istance", "dimension": 3, "normalize_rows": "false", "eta": 100, "epsilon": 0.001, "source_minclustersize": 100, "symmetry": "S", "UPLO": "L"}', '{}']
2022-01-29 16:36:02,731 - kmb.a4977f7650 - INFO - {'kernel': 'inverse-distance', 'dimension': 3, 'normalize_rows': 'false', 'eta': 100, 'epsilon': 0.001, 'source_minclustersize': 100, 
'symmetry': 'S', 'UPLO': 'L'}
2022-01-29 16:36:02,736 - kmb.a4977f7650 - INFO - 
2022-01-29 16:36:02,736 - kmb.a4977f7650 - INFO - ========================================
2022-01-29 16:36:02,736 - kmb.a4977f7650 - INFO - M=5,000 source points, N=5,000 target points in dimension 3 with a signal of dimension E=1.
2022-01-29 16:36:02,737 - kmb.a4977f7650 - INFO - kernel='inverse-distance'
2022-01-29 16:36:02,737 - kmb.a4977f7650 - INFO - same_points? True, normalize_rows? False, density_estimation? False.
2022-01-29 16:36:02,737 - kmb.a4977f7650 - INFO - Trying to instantiate kernel_matrix_benchmarks.algorithms.htool.HtoolProduct(**{'kernel': 'inverse-distance', 'dimension': 3, 'normali
ze_rows': 'false', 'eta': 100, 'epsilon': 0.001, 'source_minclustersize': 100, 'symmetry': 'S', 'UPLO': 'L'})
2022-01-29 16:36:02,810 - kmb.a4977f7650 - INFO - [Htool warning] ACA found a zero row in a 156x156 block. Final rank is 1
2022-01-29 16:36:02,810 - kmb.a4977f7650 - INFO - [Htool warning] ACA found a zero row in a 156x156 block. Final rank is 1
2022-01-29 16:36:02,810 - kmb.a4977f7650 - INFO - [Htool warning] ACA found a zero row in a 156x156 block. Final rank is 1
2022-01-29 16:36:02,810 - kmb.a4977f7650 - INFO - [Htool warning] ACA found a zero row in a 156x156 block. Final rank is 1
....
2022-01-29 16:36:02,872 - kmb.a4977f7650 - INFO - [Htool warning] ACA found a zero row in a 156x156 block. Final rank is 1
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Precomputation done in 3.52e-02s.
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Memory usage: 5.05e+04kB.
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Running query argument group 1 of 1...
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Run 1/2...
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Block_tree_max        0.0004282
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Block_tree_mean       0.0004282
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Blocks_max    0.0274079
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Blocks_mean   0.0274079
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Compression_ratio     3.92095
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Dense_block_size_max  24649
2022-01-29 16:36:02,878 - kmb.a4977f7650 - INFO - Dense_block_size_mean 24419.8
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Dense_block_size_min  5000
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Dimension     1
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Eps   0.001
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Eta   100
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Local_size_max        5000
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Local_size_mean       5000
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Local_size_min        5000
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Low_rank_block_size_max       97969
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Low_rank_block_size_mean      27676.8
2022-01-29 16:36:02,879 - kmb.a4977f7650 - INFO - Low_rank_block_size_min       5000
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MaxBlockSize  100
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MaxClusterDepthSource 6
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MaxClusterDepthTarget 6
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinClusterDepthSource 6
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinClusterDepthTarget 6
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinClusterSizeSource  100
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinClusterSizeTarget  100
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinSourceDepth        0
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - MinTargetDepth        0
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - Number_of_MPI_tasks   1
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - Number_of_dmat        274
2022-01-29 16:36:02,880 - kmb.a4977f7650 - INFO - Number_of_false_positive      0
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Number_of_lrmat       224
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Number_of_procs       64
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Number_of_threads_per_tasks   64
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Rank_max      1
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Rank_mean     1
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Rank_min      1
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Source_size   5000
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Space_saving  0.74496
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - Target_size   5000
2022-01-29 16:36:02,881 - kmb.a4977f7650 - INFO - 
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,884 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,885 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,889 - kmb.a4977f7650 - INFO - Parameter 10 to routine DGEMM  was incorrect
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Run 2/2...
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Block_tree_max        0.0004282
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Block_tree_mean       0.0004282
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Blocks_max    0.0274079
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Blocks_mean   0.0274079
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Compression_ratio     3.92095
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Dense_block_size_max  24649
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Dense_block_size_mean 24419.8
2022-01-29 16:36:02,890 - kmb.a4977f7650 - INFO - Dense_block_size_min  5000
...
```

3. I see, thanks for your investigation! I will try to have a look too then.
4. I just run `black .` in the main folder: most files should already be formatted, so there are only a few updates per commit. And I agree with the vscode options - I have the same thing, but in my "main" settings file. I will also add a GitHub hook for auto-formatting, while we're at it :-)
5. With respect to the permutation: that's a good point! In general, I think that the purpose of the benchmarks is to have timings that reflect "real-life" use cases. We should be fairly generous with libraries in terms of what counts as a "pre-computation", since some pipelines may very well provide "structured" data to kernel routines. Realistically, do you think that some users may provide a pre-sorted source signal? (This seems likely to me, especially in the context of iterative solvers.)               

See you soon and thanks again,
Jean

**Comment by PierreMarchand20** [comment]
> 1. I was talking about adding mpi4py in the `install_requires` field of setup.py. But you seem to have done this [already](https://github.com/PierreMarchand20/htool-kernel-matrix-benchmarks/blob/b151a7d96d78e89c61f8ed3294821ea067e054c7/setup.py#L80)?

Yes, the weird thing is that it still tries to install the pybind11 module before installing mpi4py as you experienced. But I'm not an expert on setuptools, I guess adding a requirements.txt and calling `pip3 install -r requirements.txt` is a good-enough solution.

> 2. I'm a bit surprised to read that you didn't get any output in the terminal. But anyway, everything important should be in the file `kmb.log`, that you can read with e.g. `less -R kmb.log` (with colors!). For reference, in my instance, one of the experiments outputs:

That's weird, I did check `kmb.log`, but running `python3.9 run.py  --dataset  product-sphere-D3-E1-M10000-N10000-inverse-distance --force --algorithm htool-product `, I just have

```
2022-01-31 11:44:13,146 - kmb - INFO - running only htool-product
2022-01-31 11:44:13,243 - kmb - INFO - Order: [Definition(algorithm='htool-product', constructor='HtoolProduct', module='kernel_matrix_benchmarks.algorithms.htool', docker_tag='kernel-matrix-benchmarks-htool', arguments={'kernel': 'inverse-distance', 'dimension': 3, 'normalize_rows': False, 'eta': 100, 'epsilon': 0.001, 'source_minclustersize': 100, 'symmetry': 'S', 'UPLO': 'L'}, query_argument_groups=[{}])]
```

and it does produce a .hdf5 file at the end. It could be an another consequence of how dockers dealt with on macOS. You are on linux right? 

> 4. I just run `black .` in the main folder: most files should already be formatted, so there are only a few updates per commit. And I agree with the vscode options - I have the same thing, but in my "main" settings file. 

👍🏻 This would help vscode users using the correct formatter locally when working on this repo, especially since black is not the default formatter used by vscode.

> I will also add a GitHub hook for auto-formatting, while we're at it :-)

Good idea! 

> 5. With respect to the permutation: that's a good point! In general, I think that the purpose of the benchmarks is to have timings that reflect "real-life" use cases. We should be fairly generous with libraries in terms of what counts as a "pre-computation", since some pipelines may very well provide "structured" data to kernel routines. Realistically, do you think that some users may provide a pre-sorted source signal? (This seems likely to me, especially in the context of iterative solvers.)

I cannot speak for the others, but I agree it is probably standard with iterative solvers (that's what I do in htool). Generally speaking, I would say it is reasonable to add permutations in the "pre-computation" part, I just wanted to make sure :-)

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 ,

Perfect! To answer your points:

1. Sure. I understand that it's just for the benchmarks anyway (i.e. not for all users of htools) so if it works, we're all good :-)
2. Yes, I'm on Linux (both for local tests and the AWS instance). I had no idea that things could be that different with MacOS...
4. Fine for VS-Code and black, I'll do it.
5. Perfect. If the permutation is computed in the "fit()" routine but apply to sort the data in "prepare_query()", that's 100% fine I guess.

Just let me know when you think you're ready for the merge, and I'll try to iron out the last few problems!
Best regards,
Jean

**Comment by PierreMarchand20** [comment]
> 2. Yes, I'm on Linux (both for local tests and the AWS instance). I had no idea that things could be that different with MacOS...

Yes, since macOS is not linux, they use a virtual machine under the hood to run docker or something similar. I am not sure how to debug now. One thing that could help would be to compare with the brut force approach and get the real error (to check if I am computing the right thing). May be you could to the fix you wanted to do, and then I will fix and rebase the PR? 

Or we can merge, you fix what you need to fix, and I will redo a PR. In any case, this is a first iteration concerning htool, I have defined the kernel very naively just to get something running.

**Comment by jeanfeydy** [comment]
I see. I can just try to fix the error computation in your PR branch, so no need for any merge maneuver ;-)
Just to be sure: does your wrapper currently support gaussian kernels? This should be much easier to debug with 100% confidence.

**Comment by PierreMarchand20** [comment]
At the moment, it should work at least for dimension 2 and 3, but I have not tested it :D If you add a test case with gaussian kernels, I can always update what needs to be updated in htool to deal with higher dimension, and then debug with more confidence.

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 ,

I have added a gaussian example as well as a "high-precision" bruteforce mode: you should be good to go I think.
Let me know what you think :-)

**Comment by PierreMarchand20** [comment]
Everything seems to run correctly now. I still have to optimise some parts on my side, but this is probably enough for a first iteration so that others can use this as an example.

**Comment by jeanfeydy** [comment]
Hi @PierreMarchand20 ,

Ok, perfect :-)
I am re-running the benchmarks on AWS now: I will write you all an e-mail once it is online!

Thanks again, and see you soon,
Jean

**Pull request merged**
